apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: go-api-skeleton-git
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: git@github.com:yossicohn/go-api-skeleton.git #configure: change if you want to build something else, perhaps from your own local git repository.
